apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: P951FEA4DE68E13C5
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: adtracker
      defaultBucket: metrics
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
  - name: ReportingAPI
    type: yesoreyeram-infinity-datasource
    uid: PB8E226E4E220750D
    url: http://reporting:8081
    jsonData:
      views:
        - name: top-states
          url: /report/top-states
